{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "51a296be",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Vocabulary:\n",
      "['algorithms' 'analysis' 'analytics' 'and' 'applications' 'artificial'\n",
      " 'big' 'cloud' 'computing' 'css' 'data' 'database' 'deep' 'development'\n",
      " 'distributed' 'for' 'html' 'intelligence' 'introduction' 'javascript'\n",
      " 'learning' 'machine' 'management' 'methods' 'mining' 'modeling'\n",
      " 'networks' 'neural' 'numpy' 'pandas' 'predictive' 'python' 'science'\n",
      " 'sql' 'systems' 'techniques' 'to' 'using' 'visualization' 'web']\n",
      "\n",
      "Document-Term Matrix:\n",
      "       algorithms  analysis  analytics  and  applications  artificial  big  \\\n",
      "Query           0         1          0    0             0           0    0   \n",
      "D1              1         0          0    1             1           0    0   \n",
      "D2              0         1          0    1             0           0    0   \n",
      "D3              0         0          0    0             0           0    0   \n",
      "D4              0         0          0    1             0           0    0   \n",
      "D5              0         0          0    1             0           0    0   \n",
      "D6              0         0          0    0             0           0    0   \n",
      "D7              0         0          1    1             0           0    1   \n",
      "D8              0         0          0    1             0           1    0   \n",
      "D9              0         0          0    1             0           0    0   \n",
      "D10             0         1          0    1             0           0    0   \n",
      "\n",
      "       cloud  computing  css  ...  predictive  python  science  sql  systems  \\\n",
      "Query      0          0    0  ...           0       0        0    0        0   \n",
      "D1         0          0    0  ...           0       0        0    0        0   \n",
      "D2         0          0    0  ...           1       0        0    0        0   \n",
      "D3         0          0    0  ...           0       0        0    1        1   \n",
      "D4         0          0    0  ...           0       0        0    0        0   \n",
      "D5         0          0    0  ...           0       0        0    0        0   \n",
      "D6         0          0    1  ...           0       0        0    0        0   \n",
      "D7         0          0    0  ...           0       0        0    0        0   \n",
      "D8         0          0    0  ...           0       0        1    0        0   \n",
      "D9         1          1    0  ...           0       0        0    0        1   \n",
      "D10        0          0    0  ...           0       1        0    0        0   \n",
      "\n",
      "       techniques  to  using  visualization  web  \n",
      "Query           0   0      0              0    0  \n",
      "D1              0   1      0              0    0  \n",
      "D2              0   0      0              0    0  \n",
      "D3              0   0      1              0    0  \n",
      "D4              0   0      0              0    0  \n",
      "D5              1   0      0              0    0  \n",
      "D6              0   0      1              0    1  \n",
      "D7              0   0      0              1    0  \n",
      "D8              0   0      0              0    0  \n",
      "D9              0   0      0              0    0  \n",
      "D10             0   0      1              0    0  \n",
      "\n",
      "[11 rows x 40 columns]\n",
      "\n",
      "Cosine Similarity Scores:\n",
      "  Document  Cosine Similarity\n",
      "1       D2           0.790569\n",
      "4       D5           0.507093\n",
      "7       D8           0.507093\n",
      "0       D1           0.338062\n",
      "9      D10           0.338062\n",
      "3       D4           0.200000\n",
      "6       D7           0.200000\n",
      "2       D3           0.000000\n",
      "5       D6           0.000000\n",
      "8       D9           0.000000\n",
      "Ranking of Documents\n",
      "\n",
      "1. D2\n",
      "   Score : 0.7906\n",
      "   Course: Machine Learning for Data Analysis and Predictive Modeling\n",
      "\n",
      "2. D5\n",
      "   Score : 0.5071\n",
      "   Course: Data Mining Techniques and Machine Learning Methods\n",
      "\n",
      "3. D8\n",
      "   Score : 0.5071\n",
      "   Course: Artificial Intelligence Machine Learning and Data Science\n",
      "\n",
      "4. D1\n",
      "   Score : 0.3381\n",
      "   Course: Introduction to Machine Learning Algorithms and Applications\n",
      "\n",
      "5. D10\n",
      "   Score : 0.3381\n",
      "   Course: Data Analysis using Python Pandas and NumPy\n",
      "\n",
      "6. D4\n",
      "   Score : 0.2000\n",
      "   Course: Deep Learning and Neural Networks\n",
      "\n",
      "7. D7\n",
      "   Score : 0.2000\n",
      "   Course: Big Data Analytics and Data Visualization\n",
      "\n",
      "8. D3\n",
      "   Score : 0.0000\n",
      "   Course: Database Management Systems using SQL\n",
      "\n",
      "9. D6\n",
      "   Score : 0.0000\n",
      "   Course: Web Development using HTML CSS JavaScript\n",
      "\n",
      "10. D9\n",
      "   Score : 0.0000\n",
      "   Course: Cloud Computing and Distributed Systems\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "import pandas as pd\n",
    "\n",
    "documents = {\n",
    "    \"D1\": \"Introduction to Machine Learning Algorithms and Applications\",\n",
    "    \"D2\": \"Machine Learning for Data Analysis and Predictive Modeling\",\n",
    "    \"D3\": \"Database Management Systems using SQL\",\n",
    "    \"D4\": \"Deep Learning and Neural Networks\",\n",
    "    \"D5\": \"Data Mining Techniques and Machine Learning Methods\",\n",
    "    \"D6\": \"Web Development using HTML CSS JavaScript\",\n",
    "    \"D7\": \"Big Data Analytics and Data Visualization\",\n",
    "    \"D8\": \"Artificial Intelligence Machine Learning and Data Science\",\n",
    "    \"D9\": \"Cloud Computing and Distributed Systems\",\n",
    "    \"D10\": \"Data Analysis using Python Pandas and NumPy\"\n",
    "}\n",
    "\n",
    "query = \"Machine Learning for Data Analysis\"\n",
    "\n",
    "\n",
    "vectorizer = CountVectorizer(binary=True)\n",
    "X = vectorizer.fit_transform([query] + list(documents.values()))\n",
    "\n",
    "print(\"Vocabulary:\")\n",
    "print(vectorizer.get_feature_names_out())\n",
    "\n",
    "df = pd.DataFrame(\n",
    "    X.toarray(),\n",
    "    index=[\"Query\"] + list(documents.keys()),\n",
    "    columns=vectorizer.get_feature_names_out()\n",
    ")\n",
    "\n",
    "print(\"\\nDocument-Term Matrix:\")\n",
    "print(df)\n",
    "\n",
    "query_vector = X[0]\n",
    "document_vectors = X[1:]\n",
    "\n",
    "similarities = cosine_similarity(query_vector, document_vectors)[0]\n",
    "\n",
    "result = pd.DataFrame({\n",
    "    \"Document\": documents.keys(),\n",
    "    \"Cosine Similarity\": similarities\n",
    "})\n",
    "\n",
    "result = result.sort_values(\n",
    "    by=\"Cosine Similarity\",\n",
    "    ascending=False\n",
    ")\n",
    "\n",
    "print(\"\\nCosine Similarity Scores:\")\n",
    "print(result)\n",
    "\n",
    "result.reset_index(drop=True, inplace=True)\n",
    "\n",
    "print(\"Ranking of Documents\\n\")\n",
    "\n",
    "for i in range(len(result)):\n",
    "    doc = result.loc[i, \"Document\"]\n",
    "    score = result.loc[i, \"Cosine Similarity\"]\n",
    "\n",
    "    print(f\"{i+1}. {doc}\")\n",
    "    print(f\"   Score : {score:.4f}\")\n",
    "    print(f\"   Course: {documents[doc]}\\n\")\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
